# General
model=OpenIPC ShowMe
manufacturer=OpenIPC
firmware_ver=2.3.7.x
hardware_id=HI5518EV200_OV9732_NOR16M
serial_num=OPENIPC.ORG
ifs=wlan0
port=8080
scope=onvif://www.onvif.org/Profile/Streaming
user=admin
password=123456

#Profile 0
name=Profile_0
width=1920
height=1080
url=rtsp://%s/stream=0
snapurl=http://%s/image.jpg
type=H265
audio_encoder=AAC
audio_decoder=G711

#Profile 1
name=Profile_1
width=1280
height=720
url=rtsp://%s/stream=1
snapurl=http://%s/image.jpg?width=1280&height=720
type=H265
audio_encoder=AAC
audio_decoder=NONE

#PTZ
ptz=1
move_left=/usr/bin/ansjer-ptz -d l
move_right=/usr/bin/ansjer-ptz -d r
move_up=/usr/bin/ansjer-ptz -d u
move_down=/usr/bin/ansjer-ptz -d d
move_stop=/usr/bin/ansjer-ptz -d s
move_preset=/usr/bin/ansjer-ptz -g %d
set_preset=/usr/bin/ansjer-ptz -p %d
goto_home_position=/usr/bin/ansjer-ptz -g 1
get_presets=cat /etc/ptz_presets.conf

#RELAY OUTPUTS
#LIGHT WHITE
idle_state=close
close=/usr/sbin/gpio clear 59
open=/usr/sbin/gpio set 59
